[book]
authors = ["Lucas Javaudin"]
language = "en"
src = "src"
title = "METROPOLIS2 The Book"
description = "General documentation for the transport simulator METROPOLIS2"

[output.html]
theme = "theme"
default-theme = "light"
preferred-dark-theme = "ayu"
smart-punctuation = true
mathjax-support = true
